name: Vite React CI
run-name: ${{ github.actor }} is deploying vite app.

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies for vite app
        run: npm install

      - name: Run build
        run: npm run build
